### ISSUE TITLE
Overlapping Seasons cause a problem

### ISSUE THREAD

**Issue by jbfraser1** [jbfraser1/SailScores#126]
When a race is set to a date that belongs to more than one season, errors will occur when retrieving the race.

Possible solutions:
1. Don't allow the creation or edit of a season that creates an overlap of seasons.
2. Allow races to belong to more than one season.

Seems like 1. will be easier.

(Also, while testing, make sure that seasons spanning two or more years don't cause errors.)

**Comment by natrad100** [comment]
1 is a sensible option
