### ISSUE TITLE
Unable to create a race within a regatta

### ISSUE THREAD

**Issue by natrad100** [jbfraser1/SailScores#128]
**Describe the bug**
Unable to create a race within a regatta. 

**To Reproduce**
1. https://www.sailscores.com/ASSATEST/Regatta
2. Click on "National CHampionships Test"
3. Click [New Race](https://www.sailscores.com/ASSATEST/Race/Create?regattaId=d6450298-ae0b-4384-b671-08d80b3a98c7&returnUrl=https%3A%2F%2Fwww.sailscores.com%2FASSATEST%2FRegatta%2F2020-21%2520Season%2FNationalChampionshipsTest)
4. Add a fleet, add some results.
5. 404 - Page attempting to access (https://www.sailscores.com/ASSATEST/Race/Create?returnurl=https%3A%2F%2Fwww.sailscores.com%2FASSATEST%2FRegatta%2F2020-21%2520Season%2FNationalChampionshipsTest)

**Comment by jbfraser1** [comment]
Reproduced the issue. Still figuring out the cause.

**Comment by jbfraser1** [comment]
This should now be fixed. Of course, let me know/reopen this if the regatta races still won't save.

**Comment by natrad100** [comment]
So the first race went in beautifully, and now an issue regarding adding another race as well.

Also don't feel that you have to fix these straight away! I'm just working out what can be done. Also getting my head around the implementation to try and make suggested changes that way
