### ISSUE TITLE
Series/Race Tab not updating Data? or maybe linking properly

### ISSUE THREAD

**Issue by natrad100** [jbfraser1/SailScores#129]
**Describe the bug**
Initial issue using a '/' within a season name (makes sense to a web designer but to to everyone). When the season name was changed this was not reflected on the page and may have broken many of the other tab aspects

**To Reproduce**
1. If you go to (https://www.sailscores.com/ASSATEST/Series) it will show the old name and the old 'state championships series' that cannot be accessed
2. If you go to (https://www.sailscores.com/ASSATEST/Race) you will see the old renamed series and a new series
3. The links to all of the races, not of the links are working except for the 2020 NSW State Championships.

**Comment by natrad100** [comment]
Further to update this - when the dates where changed (because I can't delete) on the season, it began to operate as expected!

**Comment by jbfraser1** [comment]
I'll look into this and see if I can figure out what happened.
Related info:
One of the techniques that SailScores uses: when a series is first created, a URL-safe version of the series name is created and saved: in theory, "Dave's BEST!/Worst Series" should get a URL name of "DavesBestWorstSeries" or similar. This name doesn't get changed when the series name changes, so external links to the series won't get broken. That is, the slash should work in the series name.

I considered keeping a table of series names, and updating this URL name, but went with the simpler approach for now. This feature/weirdness isn't really shown in the UI anywhere.

**Comment by jbfraser1** [comment]
I confirmed that season names don't currently handle slashes and other none URL friendly characters. Fix expected today.

**Comment by jbfraser1** [comment]
Fix is still getting tested.

**Comment by jbfraser1** [comment]
Fix confirmed to work, Created a 21/22 season, which then got a "UrlName" of 2122, and series and race links used that.
