### ISSUE TITLE
Float / Rounding error in Regatta Results

### ISSUE THREAD

**Issue by natrad100** [jbfraser1/SailScores#131]
**Describe the bug**
Results have 0.5 added to each result (for low score points)

**To Reproduce**
Add results to any race within a regatta

**Comment by jbfraser1** [comment]
I reproduced the problem. It's really weird and surprising. I don't know what the cause is, but this should be fixed in the ~6 hours.

**Comment by jbfraser1** [comment]
I haven't found the cause yet. Looks like it is related to the first time a race is saved for a regatta. Editing the race (saving it a second time) seems to generate correct results for the regatta. Might be related to the code that figures out the trend.

Still looking.
